### ISSUE TITLE
How to check if Node.js window is active?

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/active-win#12]
The `pid` property is of Terminal.app, not the specific window, where there can be multiple.

**Comment by sindresorhus** [comment]
From the docs:

> pid - Process ID of the **app owning the window**

**Comment by tiangolo** [comment]
@stevenvachon  Check https://github.com/sindresorhus/active-win#result

It seems you are looking for:

> * `id` - Window ID

not for:

> * `pid` - Process ID of the app owning the window

**Comment by stevenvachon** [comment]
Yes, I read the docs. I guess that I should have said that getting the app owning the window is useless (to me).

The `id` property doesn't seem to align with anything that I can use either, such as `process.pid` or `require('posix').getppid()`.

**Comment by tiangolo** [comment]
Well, the Node.js process is running in your Terminal app, isn't it?

**Comment by stevenvachon** [comment]
```js
const {sync:activeWindow} = require('active-win');
const {getppid:parentPID} = require('posix');

console.log(process.pid, activeWindow().id, activeWindow().pid, parentPID());
//-> 77532 95175 1581 76549
```

**Comment by sindresorhus** [comment]
> Besides, what good is it to know that any one of the multiple Terminal windows is focused?

For your use-case it's not, but this module was not made for your use-case either. The system has no knowledge of what processes you run inside Terminal.app. You could maybe combine this module with some AppleScript to solve your problem.

**Comment by tiangolo** [comment]
I'm not a macOS expert (I'm more on the Linux side) but I imagine that if you have different Terminal windows they will be created by different processes. And if they are created by the same process (same PID), still, they will have a specific window ID.

Here's what I think that could be happening. These are the IDs I think you are getting:

* `77532`: the current Node.js process. Not because it is what you are running it means that it is the owner / creator of the current window.
* `95175`: the ID of the current window. If you have several Terminal windows open, this ID is the one that identifies the current window from the others.
* `1581`: the process that created / owns the window, probably `Terminal.app`
* `76549`: the parent process of the Node.js process, not necessarily `Terminal.app`, maybe a children of `Terminal.app`, it's probably the PID of `bash`.
